### PR TITLE
Fix crash in UpvoteService due to incorrect injection

### LINKED ISSUE #550: [Bug] Crash on UpvoteStoryService.handleActionUpvote
```
Fatal Exception: java.lang.NullPointerException
Attempt to invoke virtual method 'boolean io.plaidapp.core.designernews.data.login.LoginRepository.isLoggedIn()' on a null object reference
```

Looks like we're not injecting the LoginRepository correctly.

### PR DESCRIPTION
**Pull request by florina-muntenescu**
Fixes #550

### CODE REVIEW

File: core/src/main/java/io/plaidapp/core/designernews/data/votes/UpvoteStoryService.java [hunk 1]
```diff
@@ -36,6 +37,7 @@
 
     public UpvoteStoryService() {
         super("UpvoteStoryService");
+        Injector.inject(this);
```
Comment (ataulm) [inline core/src/main/java/io/plaidapp/core/designernews/data/votes/UpvoteStoryService.java]: yep, that seems like the issue.

File: core/src/main/java/io/plaidapp/core/dagger/designernews/Injector.kt [hunk 2]
```diff
@@ -0,0 +1,45 @@
...
+import io.plaidapp.core.designernews.data.api.DesignerNewsService
+import io.plaidapp.core.designernews.data.login.LoginLocalDataSource
+import io.plaidapp.core.designernews.data.votes.UpvoteStoryService
+import retrofit2.converter.gson.GsonConverterFactory
+
+/**
+ * Injector for [UpvoteStoryService].
+ */
+
+fun inject(service: UpvoteStoryService) {
```
Comment (ataulm) [inline core/src/main/java/io/plaidapp/core/dagger/designernews/Injector.kt]: Would it be easy to move UpvoteStoryService to `designernews` instead of fixing this stuff in `core`?
